# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lx < Formula
  desc "Interface by Human, Logic by AI."
  homepage "https://github.com/chebread/lx"
  version "1.1.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chebread/lx/releases/download/v1.1.0/lx_darwin_amd64.tar.gz"
      sha256 "b4d21faffb57ff04cc780c9673ec143ad69f54a78f257972604793fe74520cb1"

      def install
        bin.install "lx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chebread/lx/releases/download/v1.1.0/lx_darwin_arm64.tar.gz"
      sha256 "2ab4a74b4b2a58f498a9b8270393f738440071f0b58f3fff8592bb1514f31785"

      def install
        bin.install "lx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chebread/lx/releases/download/v1.1.0/lx_linux_amd64.tar.gz"
        sha256 "2c3af5ff519bb501d215022002610df3d7b85fed0ce68f7f45a210b910b4026a"

        def install
          bin.install "lx"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chebread/lx/releases/download/v1.1.0/lx_linux_arm64.tar.gz"
        sha256 "75f5ba5b3c0687bf21873b7efcceb13d437d81e24c85d3bf344d101809f750a6"

        def install
          bin.install "lx"
        end
      end
    end
  end

  test do
    system "#{bin}/lx --version"
  end
end
