# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lx < Formula
  desc "Controllable AI for Gophers."
  homepage "https://github.com/chebread/lx"
  version "0.1.2"
  license "AGPL-3.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/chebread/lx/releases/download/v0.1.2/lx_darwin_amd64.tar.gz"
    sha256 "46643c88191401482f5ccac917f3128176396110b5367a7131e176aeddc26d45"

    def install
      bin.install "lx"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/chebread/lx/releases/download/v0.1.2/lx_darwin_arm64.tar.gz"
    sha256 "582f3c987e404a588eecccde0a8a0a309bb941f285a57208ece3798ec5f5f452"

    def install
      bin.install "lx"
    end
  end

  test do
    system "#{bin}/lx --version"
  end
end
