# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lx < Formula
  desc "Interface by Human, Logic by AI."
  homepage "https://github.com/chebread/lx"
  version "2.1.0"
  license "AGPL-3.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/chebread/lx/releases/download/v2.1.0/lx_darwin_amd64.tar.gz"
    sha256 "415511ac7f42bf30d26461b5fe076823b184bb66dbf7dd383bbebbd7eb0c6604"

    def install
      bin.install "lx"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/chebread/lx/releases/download/v2.1.0/lx_darwin_arm64.tar.gz"
    sha256 "cc0cae52aaf7d3d44714d6fa55f1bb92c797435d431db89ddd31d165118cf61f"

    def install
      bin.install "lx"
    end
  end

  test do
    system "#{bin}/lx --version"
  end
end
